import React from "react";

export default function FooterLower() {
  return (
    <div>
      <div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
        <div>
          <h4>
            <p></p>
          </h4>
        </div>
      </div>
      <div>
        <a href="/">Conditions of Use</a>
        <a href="/">Privacy Notice</a>
        <a href="/">Your Ads Privacy Choices</a>
      </div>
      <p>© 1996-2023, Amazon.com, Inc. or its affiliates</p>
    </div>
  );
}
